spring:
  application:
    name: turbine
server:
  port: 8989
turbine:
  app-config: ingredient-client,ingredient-service
  cluster-name-expression: "'default'"
eureka:
  client:
    service-url:
      defaultZone:
        http://eureka-host-1:8761/eureka,
        http://eureka-host-2:8762/eureka,
        http://eureka-host-3:8763/eureka
