spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sbrace/config-repository
          search-paths: config,more*
          default-label: main
server:
  port: 8888