server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-host-1:8761/eureka,http://eureka-host-2:8762/eureka,http://eureka-host-3:8763/eureka
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sbrace/config-repository
          search-paths: ingredient
          default-label: main
