server:
  port: 8081

spring:
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    broker-url: tcp://localhost:61616
    user: username
    password: password
    embedded:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    template:
      receive-timeout: 30000
      exchange: tacocloud.order
      routing-key: kitchens.central
  json.type.mapping: cat:sss
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos.*
        spring.json.type.mapping: order:tacos.kitchen.messaging.domain.Order
logging:
  level:
    root: info