spring:
  application:
    name: ingredient-client
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka-host-1:8761/eureka,
        http://eureka-host-2:8762/eureka,
        http://eureka-host-3:8763/eureka
