server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/tacocloud
    username: root
    password: 1111
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      # set always at first time
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    root: debug